apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: frontend
spec:
  secretName: frontend-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - frontend.601a4100d9f64def847e.eastus.aksapp.io # replace cluster specific dns zone with your HTTP Routing DNS Zone name
  acme:
    config:
    - http01:
        ingressClass: addon-http-application-routing
      domains:
      - frontend.601a4100d9f64def847e.eastus.aksapp.io  # replace cluster specific dns zone with your HTTP Routing DNS Zone name